### ISSUE TITLE
Audio is not synced

### ISSUE THREAD

**Issue by fu-hsi** [osmanovv/auxmic#22]
Hi.
I can't get this app work properly.
I downloaded sources to check where is the problem with wav files.
Application doesn't display any error, but generate empty video file.
The problem is with wav, it can't be combined with mp4 container, this is normal but user doesn't know that without error message.
The biggest problem is that this app doesn't sync audio at all.
I have made short 30s long video clip and I had offset different for each audio format (wav, mp3 stereo, mp3 mono).
None of generated file was synced correctly.
My test clip contains 3 claps at the beginning and normal speaking.

**Comment by osmanovv** [comment]
Hi!

The app is just syncing audio - calculates an offset from your high-quality audio file. It uses FFmpeg to produce a video with a synced source.

For short files (30 sec is very short) try to narrow the window function length `L` in `\auxmic.ui\mainwindow.xaml.cs` and find a suitable value for `FreqRangeStep`:
```
        private SyncParams _syncParams = new SyncParams
        {
            L = 128,
            FreqRangeStep = 20,
            WindowFunction = WindowFunctions.Hamming
        };
```
(I plan to expose these values to the settings window next time.)

> wav, mp3 stereo, mp3 mono

Before syncing, it converts audio to WAV and resamples audio from a video (or better quality audio) source to the same sample rate as in your high-quality source file. For syncing it uses only one channel.

To check the issue with exporting synced video file try to execute this command:
`ffmpeg.exe -i [videoFilePath] -ss [offset] -i [audioFilePath] -c copy -map 0:v:0 -map 1:a:0 -shortest [targetFilePath]`
where `offset` is in [time duration format](https://ffmpeg.org/ffmpeg-utils.html#Time-duration): `[-][HH:]MM:SS[.m...]`

Could you provide your samples?

**Comment by fu-hsi** [comment]
Hi.
I made another test.

1. Audio-2021-01-13-20-26-53.mp3 - 51s duration converted from WAV
2. YDXJ1931.mp4 - 15s duration
3. YDXJ1932.mp4 - 9s duration
4. YDXJ1933.mp4 - 9s duration

Results:

1. -0:00:02.148
2. 0:00:00.911
3. 0:00:00.882

Expected results:

1. 00:00:00.000
2. 00:00:25.000
3. 00:00:41.000

Files contains my speaking including beeps from camera when it starts recording, nothing else.

**Comment by fu-hsi** [comment]
After suggested modifications with new SyncParams data:

1. -0:00:04.772
2. -0:00:00.206
3. -0:00:06.011

I'd rather not send files with my conversations and video :)
Believe me, this is an ordinary conversation to a camera like one, two, three, etc.

**Comment by fu-hsi** [comment]
I found alternative solution :)
DaVinci Resolve 16 with Auto Sync Audio by Waveform.
Works like a charm!
Next step is to export audio or use Resolve for movie create (I have too weak PC for that software).
We can use exported audio directly or replace original audio with ffmpeg.
Now we can use video clips in any video software we like :)

**Comment by osmanovv** [comment]
I'm glad that you have found the solution.

Unfortunately, I'm not able to check this issue without sample files. Try to use longer records.

> I'd rather not send files with my conversations and video :)

I understand. It's not necessary to use the whole video, audio track is enough.
