### ISSUE TITLE
Improve usability/UI

### ISSUE THREAD

**Issue by osmanovv** [osmanovv/auxmic#6]
- [x] Media file names clarified.
- [x] Hide `Save` button on hiqh quality source (as there is nothing to export).
- [x] Repalce `Save` button to dropdown button with options to `export synchronized audio` & `export media with synchronized audio (FFmpeg)`.

**Comment by kerryland** [comment]
How about replacing "drop master file here" with "Drop high quality audio source here", and
"drop other media files here" becomes "Drop media to synchronize here".

Also I think you should completely remove the "Save" button from the "master file" row. It's currently disabled, which suggests it can sometime be enabled, which isn't possible, right?

**Comment by fu-hsi** [comment]
For me, the "Export all" button is missing. When someone has a hundred files, there is no point in expanding menus for each item.
